name: Telegram_yml_script  # nombre del workflow que ver√°s en GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:  # permite correr manualmente
  schedule:
    - cron: "30 16 * * *"  # runs every day at 13:30 Argentina (UTC-3)

jobs:
  db_and_telegram_job:  # nombre interno del job
    runs-on: ubuntu-latest

    env:  
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      DB_URL: ${{ secrets.DB_URL }}

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.12  

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Telegram script
        run: python main_script.py
        
